### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by chandresh-pancholi** [uber/tchannel-java#136]
Hi Team,

I wanted to know the process of contribution in Tchannel-java as a non Uber employee.
I have went through the codebase and set it up in local.

There is no google group mentioned so posting it here.

**Comment by blampe** [comment]
Hi Chandresh! We'd love to have you contribute. Before we can merge any PRs we would just need you to fill out the [Uber CLA](https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform).
