### ISSUE TITLE
Java Hyperbahn Client

### ISSUE THREAD

**Issue by willsalz** [uber/tchannel-java#23]
We should get a minimal Hyperbahn client up and running on top of tchannel-java.

The implementation can be inside the parent TChannel project but in a different module ( probably, `hyperbahn` or something ). The only dependency should be `tchannel-core`, with no Thrift dependencies since Hyperbahn speaks JSON-as-TChannel

**Comment by willsalz** [comment]
Working on this on [hyperbahn-client](/uber/tchannel-java/tree/willsalz/hyperbahn-client)

**Comment by ShanniLi** [comment]
done
