### ISSUE TITLE
TChannel behavior with ttl 0

### ISSUE THREAD

**Issue by truncs** [uber/tchannel-java#48]
I was testing some stuff on hyperbahn when I found this

TchannelProtocolInvalidTtlError: Got an invalid ttl. Expected positive ttl but got 0
00: 0090 0300 0000 0000 0000 0000 0000 0000  ................  UInt16BE(144) UInt8(3) UInt32BE(0)
10: 0000 0000 0000 0000 0000 0000 0000 0000  ................  UInt8(0) UInt32BE(0)
20: 0000 0000 0000 0000 0000 0000 0000 0968  ...............h
30: 7970 6572 6261 686e 0202 636e 0b70 696e  yperbahn..cn.pin
40: 672d 7365 7276 6572 0261 7304 6a73 6f6e  g-server.as.json
50: 0000 0261 6400 027b 7d00 357b 2273 6572  ...ad..{}.5{"ser
60: 7669 6365 7322 3a5b 7b22 7365 7276 6963  vices":[{"servic
70: 654e 616d 6522 3a22 7069 6e67 2d73 6572  eName":"ping-ser
80: 7665 7222 2c22 636f 7374 223a 307d 5d7d  ver","cost":0}]}
session=3 127.0.0.1:56981 <-- 127.0.0.1:21306 frame=4294967295 type=0xff
ERROR[ProtocolError] id=0xffffffff (4294967295)
tracing: spanid=0000000000000000 parentid=0000000000000000 traceid=0000000000000000 flags=0x00
message
    00: 7463 6861 6e6e 656c 2072 6561 6420 6661  tchannel read fa
    10: 696c 7572 653a 2047 6f74 2061 6e20 696e  ilure: Got an in
    20: 7661 6c69 6420 7474 6c2e 2045 7870 6563  valid ttl. Expec
    30: 7465 6420 706f 7369 7469 7665 2074 746c  ted positive ttl
    40: 2062 7574 2067 6f74 2030                  but got 0

So I am not sure if this is defined somewhere in the protocol but if that is the case for every tchannel then

1) Clients should not be able to make requests with 0 ttl
2) Server should raise an error if it receives any requests with 0 ttl
3) There should be some sane default for this ?

**Comment by truncs** [comment]
Let me know what do you think @willsalz

**Comment by willsalz** [comment]
yeah I need to expose that…thanks for the bug.

**Comment by willsalz** [comment]
Will be resolved in #52

**Comment by willsalz** [comment]
#52 merged.
