### ISSUE TITLE
Appropriate versioning before releasing it to maven repository 

### ISSUE THREAD

**Issue by truncs** [uber/tchannel-java#49]
The current version is set 1.0-SNAPSHOT, we have couple of options over here

1. Just go ahead with this scheme and mark the stable releases as 1.0 and all others (including alpha and beta) as 1.0-SNAPSHOT
2. Use netty style versioning where there are several x.x.x.AlphaN x.x.x.BetaN releases before a final x.x.x.Final release
3. Use semver style versioning

**Comment by willsalz** [comment]
I'd prefer SemVer if that's acceptable in the Java community.

**Comment by truncs** [comment]
Some projects do use SemVer.

**Comment by willsalz** [comment]
So we're going to go with [SemVer](http://semver.org) for releases, including caveats for `major version zero` *as well as* support for Nightlies a.k.a. SNAPSHOT releases. I won't plan on releasing SNAPSHOT builds but it's good to keep them in non-release code branches as an indicator of instability.
