### ISSUE TITLE
TChannel object can not set host?

### ISSUE THREAD

**Issue by xiexiaodong** [uber/tchannel-java#54]
we can use the following code to set`TChannel` Object Parameter , but we find `TChaneel` have not `setServerHost(String host)` ,I find TChannel.Builder Class constructor make the host: `InetAddress.getLocalHost();` 
```java
TChannel tchannel = new TChannel.Builder("ping-server")
                .register("ping", new PingRequestHandler())
                .setServerPort(this.port)
                .build();
-------------------------------------------------------------------------
public Builder(String service) throws UnknownHostException {
            if (service == null) {
                throw new NullPointerException("`service` cannot be null");
            }
            this.service = service;
            this.host = InetAddress.getLocalHost();
        }
```
for example:we should set our test case‘s host is` localhost `or `127.0.0.1`.Can we make it free?.

**Comment by willsalz** [comment]
From what I understand you would like the ability to listen on loopback address. Seems reasonable.
