### ISSUE TITLE
tchannel-java doesn't work with arg scheme raw

### ISSUE THREAD

**Issue by truncs** [uber/tchannel-java#62]

**Comment by willsalz** [comment]
So some context here: we don't have a way to 'dispatch', e.g. route a request to a custom handler, because the unspecified semantics of arg{1,2,3}.

We need to figure out a good model of handling and send Raw Requests with this limitation.

**Comment by truncs** [comment]
Also the call API require that the response class is sent which doesn't make any sense for raw request and resposne.

**Comment by truncs** [comment]
This has been resolved with some recent commits

**Comment by willsalz** [comment]
:tada:
